:sectnums:

==== Область применения

Перевод средств от ФЛ-отправителя ФЛ-получателю.

==== Основной сценарий обмена

[plantuml, format="png", id="exchange_3"]

----
include::../C2C/PlantUML/C2C.puml[]
----

===== Описание

Успешный процесс перевода средств между СЦР клиентов ФЛ.

===== Применяемые форматы сообщений

    * Запрос возможности C2C перевода ЦР (*cbdc.012 C2CPossibilityRequest*); <<Описание>>
    * Ответ на запрос возможности C2C перевода ЦР (cbdc.013 C2CPossibilityResponse);
    * Дополнительная информация к ответу на запрос возможности (cbdc.014 InfoResponse);
    * Распоряжение Клиента на перевод ЦР (С2С) (cbdc.003 CustomerDCTransferC2C);
    * Извещение Клиента - получателя об исполнении перевода ЦР (С2С) (cbdc.777 DCTransferC2CRecipientNotification);
    * Дополнительная информация к уведомлению получателя перевода (cbdc.778 InfoRecipientNotification);
    * Извещение Клиента - плательщика об исполнении перевода ЦР (С2С) (cbdc.777 DCTransferC2CSenderNotification).

===== Условие применения

Намерение Клиента-ФЛ по переводу ЦР с СЦР Клиента-ФЛ-плательщика на СЦР Клиента-ФЛ-получателя по идентификатору (номеру телефона) или идентификатору СЦР или номеру СЦР Клиента-получателя.

===== Последовательность обмена

. Клиент-ФЛ направляет в адрес ФП ЭС "Запрос возможности C2C перевода ЦР" (link:../../XSD/cbdc.006.001.01.B2B_2024.03.xsd[cbdc.012 C2CPossibilityRequest]).
. ФП проводит входной контроль ЭС "Запрос возможности C2C перевода ЦР" (cbdc.012 C2CPossibilityRequest) и в случае успешного прохождения контроля, перенаправляет ЭС "Запрос возможности C2C перевода ЦР" (cbdc.012 C2CPossibilityRequest) в РОРД.
. РОРД при получении запроса проводит входной контроль и следующие проверки для определения возможности перевода:
    * Контроль соответствия роли составителя запроса типу совершаемой операции;
    * Контроль наличия Клиента ФЛ-получателя в реестре Клиентов в соответствии с переданным идентификатором;

. ФП Клиента-плательщика и ФП Клиента-получателя для осуществления по операции процедур контроля по ПОД/ФТ (пост-контроль) используют соответственно расширенные атрибуты получателя, полученные в ЭС "Дополнительная информация к ответу на запрос возможности" (cbdc.014 InfoResponse), и расширенные атрибуты плательщика, полученные в ЭС "Дополнительная информация к уведомлению получателя перевода" (cbdc.778 InfoRecipientNotification).
